name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            path: ./dist/linux/linux-unpacked/**
            label: linux
          - name: windows-latest
            path: ./dist/win32/win-unpacked/**
            label: windows
    runs-on: ${{ matrix.os.name }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: npm ci
      - uses: milliewalky/setup-7-zip@v2
      - uses: ./actions/download
      - run: 7z x dist/webapp.zip webapp/ cli/
      - run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.label }}
          path: ${{ matrix.os.path }}
